// lib/localDomains.ts

// A more comprehensive list of local news domains by state.
export const localDomainsByState: Record<string, string[]> = {
  AL: [
    'al.com',
    'decaturdaily.com',
    'montgomeryadvertiser.com',
    'bhamnow.com',
    'wbrc.com',
    'waaytv.com',
  ],
  AK: [
    'adn.com',
    'ktoo.org',
    'ktuu.com',
    'alaskapublic.org',
    'ktva.com',
    'kijen.com',
  ],
  AZ: [
    'azcentral.com',
    'kpho.com',
    'tucson.com',
    'ktar.com',
    'kvoa.com',
    'abc15.com',
  ],
  AR: [
    'arkansasonline.com',
    '4029tv.com',
    'thv11.com',
    'kait8.com',
    'arklatexhomepage.com',
    'boone.news',
  ],
  CA: [
    'latimes.com',
    'sfgate.com',
    'sacbee.com',
    'mercurynews.com',
    'kpbs.org',
    'ktla.com',
  ],
  CO: [
    'denverpost.com',
    'cpr.org',
    '9news.com',
    'kdvr.com',
    'coloradoan.com',
    'csindy.com',
  ],
  CT: [
    'courant.com',
    'nhregister.com',
    'wfsb.com',
    'wtic.com',
    'newstimes.com',
    'ctpost.com',
  ],
  DE: [
    'delawareonline.com',
    'capegazette.com',
    'wjbr.com',
    'fox29.com',
    '6abc.com',
    'delmarvanow.com',
  ],
  FL: [
    'tampabay.com',
    'miamiherald.com',
    'orlandosentinel.com',
    'sun-sentinel.com',
    'wftv.com',
    'wfla.com',
  ],
  GA: [
    'ajc.com',
    'wsbtv.com',
    '11alive.com',
    'onlineathens.com',
    'savannahnow.com',
    'rome.news-leader.com',
  ],
  HI: [
    'staradvertiser.com',
    'hawaiinewsnow.com',
    'khon2.com',
    'hawaiipublicradio.org',
    'hawaiitribune-herald.com',
    'westhawaiitoday.com',
  ],
  ID: [
    'idahostatesman.com',
    'kivitv.com',
    'boisedev.com',
    'localnews8.com',
    'magicvalley.com',
    'idahopress.com',
  ],
  IL: [
    'chicagotribune.com',
    'dailyherald.com',
    'wbez.org',
    'wgntv.com',
    'abc7chicago.com',
    'crainschicago.com',
  ],
  IN: [
    'indystar.com',
    'wishtv.com',
    'wfyi.org',
    'wthr.com',
    'fortwayne.com',
    'journalgazette.net',
  ],
  IA: [
    'desmoinesregister.com',
    'whotv.com',
    'siouxcityjournal.com',
    'ktiv.com',
    'morningsun.net',
    'amestrib.com',
  ],
  KS: [
    'kansascity.com',
    'wichitaeagle.com',
    'kcpt.org',
    'fox4kc.com',
    'kshb.com',
    'lawrence.com',
  ],
  KY: [
    'kentucky.com',
    'courier-journal.com',
    'wkyufm.org',
    'lex18.com',
    'wnky.com',
    'heraldleader.com',
  ],
  LA: [
    'nola.com',
    'theadvocate.com',
    'wafb.com',
    'wwltv.com',
    'kpel965.com',
    'theadvocate.com',
  ],
  ME: [
    'pressherald.com',
    'wgme.com',
    'wmtw.com',
    'bangordailynews.com',
    'mainepublic.org',
    'mainebiz.biz',
  ],
  MD: [
    'baltimoresun.com',
    'wbaltv.com',
    'wmdt.com',
    'capgaznews.com',
    'dbknews.com',
    'marylandmatters.org',
  ],
  MA: [
    'bostonglobe.com',
    'boston.com',
    'wbur.org',
    'wbznewsradio.com',
    'wwlp.com',
    'cambridgeday.com',
  ],
  MI: [
    'freep.com',
    'mlive.com',
    'detroitnews.com',
    'clickondetroit.com',
    'wxyz.com',
    'fox2detroit.com',
  ],
  MN: [
    'startribune.com',
    'twincities.com',
    'minnesotapublicradio.org',
    'kare11.com',
    'bringmethenews.com',
    'duluthnewstribune.com',
  ],
  MS: [
    'clarionledger.com',
    'sunherald.com',
    'wjtv.com',
    'mississippilink.com',
    'msfreepress.org',
  ],
  MO: [
    'stltoday.com',
    'kansascity.com',
    'fox4kc.com',
    'kmov.com',
    'columbiamissourian.com',
    'themaneater.com',
  ],
  MT: [
    'greatfallstribune.com',
    'missoulian.com',
    'billingsgazette.com',
    'kpax.com',
    'montanadailygazette.com',
  ],
  NE: [
    'omaha.com',
    'journalstar.com',
    'kearneyhub.com',
    'lincolnjournalstar.com',
    'norfolkne.gov',
  ],
  NV: [
    'reviewjournal.com',
    'lasvegassun.com',
    'knpr.org',
    'kolo.com',
    '8newsnow.com',
  ],
  NH: [
    'unionleader.com',
    'concordmonitor.com',
    'wmur.com',
    'nhpr.org',
    'fosters.com',
  ],
  NJ: [
    'nj.com',
    'northjersey.com',
    'app.com',
    'southjerseylocalnews.com',
    'shorelocalnews.com',
    'burlingtoncountytimes.com',
  ],
  NM: [
    'abqjournal.com',
    'kob.com',
    'nmpoliticalreport.com',
    'sfnewmexican.com',
    'lasvegasoptic.com',
  ],
  NY: [
    'nytimes.com',
    'democratandchronicle.com',
    'lohud.com',
    'syracuse.com',
    'buffalonews.com',
    'lohud.com',
  ],
  NC: [
    'newsobserver.com',
    'charlotteobserver.com',
    'wfmynews2.com',
    'wral.com',
    'greensboro.com',
  ],
  ND: [
    'inforum.com',
    'bismarcktribune.com',
    'minotdailynews.com',
    'kfgo.com',
    'forumcomm.com',
  ],
  OH: [
    'cleveland.com',
    'dispatch.com',
    'wlwt.com',
    'cincinnat.com',
    'daytondailynews.com',
  ],
  OK: [
    'oklahoman.com',
    'tulsaworld.com',
    'news9.com',
    'kfor.com',
    'okcfox.com',
  ],
  OR: [
    'oregonlive.com',
    'koin.com',
    'katu.com',
    'kezi.com',
    'pamplinmedia.com',
  ],
  PA: [
    'inquirer.com',
    'pennlive.com',
    'triblive.com',
    'wpxi.com',
    'phillyvoice.com',
  ],
  RI: [
    'providencejournal.com',
    'wpri.com',
    'turnto10.com',
    'warontherocks.com', // military local angle
    'cranstononline.com',
  ],
  SC: [
    'postandcourier.com',
    'thestate.com',
    'wltx.com',
    'counton2.com',
    'greenvilleonline.com',
  ],
  SD: [
    'argusleader.com',
    'rapidcityjournal.com',
    'keloland.com',
    'mitchellrepublic.com',
  ],
  TN: [
    'tennessean.com',
    'wkrn.com',
    'wsmv.com',
    'knoxnews.com',
    'memphisdailynews.com',
  ],
  TX: [
    'houstonchronicle.com',
    'dallasnews.com',
    'statesman.com',
    'dfw.cbslocal.com',
    'khou.com',
    'texasmonthly.com',
  ],
  UT: [
    'sltrib.com',
    'ksl.com',
    'fox13now.com',
    'utahpublicradio.org',
    'utahpolicy.com',
  ],
  VT: [
    'burlingtonfreepress.com',
    'vtdigger.org',
    'burtoncom.com',
    'mychamplainvalley.com',
  ],
  VA: [
    'richmond.com',
    'pilotonline.com',
    'timesdispatch.com',
    'wric.com',
    'wjla.com',
  ],
  WA: [
    'seattletimes.com',
    'komonews.com',
    'kiro7.com',
    'spokesman.com',
    'bellevuereporter.com',
  ],
  WV: [
    'wvgazettemail.com',
    'metronews.com',
    'heraldmailmedia.com',
    'woay.com',
  ],
  WI: [
    'jsonline.com',
    'chippewa.com',
    'biztimes.com',
    'wauwatosanow.com',
  ],
  WY: [
    'trib.com',
    'gillettenewsrecord.com',
    'wyomingnewsnow.tv',
    'codyenterprise.com',
  ],
};

// Expand national outlets to 20 top domains:
export const nationalDomains = [
  'cnn.com',
  'nytimes.com',
  'washingtonpost.com',
  'usatoday.com',
  'npr.org',
  'reuters.com',
  'apnews.com',
  'bbc.com',
  'bloomberg.com',
  'forbes.com',
  'politico.com',
  'huffpost.com',
  'cbsnews.com',
  'abcnews.go.com',
  'nbcnews.com',
  'thehill.com',
  'msnbc.com',
  'time.com',
  'axios.com',
  'vice.com',
];
